[[runners]]
  environment = ["FF_NETWORK_PER_BUILD=1"]
  request_concurrency = 10

  [runners.docker]
    image = "alpine:3.20"
    privileged = false
    disable_cache = false
    pull_policy = "if-not-present"
    shm_size = 0
    volumes = ["/cache"]
