version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: mynginx
    ports:
      - "8088:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx